---
apiVersion: v1
kind: Namespace
metadata:
  name: mk-sentiment-fastapi-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mk-sentiment-fastapi
  namespace: mk-sentiment-fastapi-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mk-sentiment-fastapi
  template:
    metadata:
      labels:
        app: mk-sentiment-fastapi

    spec:
      containers:
        - name: mk-sentiment-fastapi
          image: anixdrone/mk-sentiment-fastapi
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres/macedonian_sentiment"
          ports:
            - containerPort: 5000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mk-sentiment-fastapi-service
  namespace: mk-sentiment-fastapi-ns
spec:
  type: ClusterIP
  ports:
    - port: 5000
  selector:
    app: mk-sentiment-fastapi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mk-sentiment-fastapi-ingress
  namespace: mk-sentiment-fastapi-ns
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: mk-sentiment-fastapi-service
                port:
                  number: 5000
            path: /api
            pathType: Prefix